// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<main.Settings>;

export function OpenFile():Promise<Record<string, string>>;

export function QueryAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReopenWithEncoding(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveFileWithEncoding(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
