// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmCloseTab(arg1:string,arg2:boolean):Promise<boolean>;

export function ForceOpenFileByPath(arg1:string):Promise<Record<string, string>>;

export function GetDisplayName(arg1:string):Promise<string>;

export function GetPendingFilePath():Promise<string>;

export function HideWindow():Promise<void>;

export function LoadSettings():Promise<main.Settings>;

export function LogMessage(arg1:string):Promise<void>;

export function OpenFile():Promise<Record<string, string>>;

export function OpenFileByPath(arg1:string):Promise<Record<string, string>>;

export function OpenNewWindow(arg1:string):Promise<void>;

export function PrintHTML(arg1:string):Promise<void>;

export function PrintText(arg1:string):Promise<void>;

export function QueryAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReopenWithEncoding(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveFileWithEncoding(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectFileForLink():Promise<string>;

export function SetDirty(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
