// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function QueryAI(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryAI'](arg1, arg2, arg3);
}

export function ReopenWithEncoding(arg1, arg2) {
  return window['go']['main']['App']['ReopenWithEncoding'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileWithEncoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileWithEncoding'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
