// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmCloseTab(arg1, arg2) {
  return window['go']['main']['App']['ConfirmCloseTab'](arg1, arg2);
}

export function ForceOpenFileByPath(arg1) {
  return window['go']['main']['App']['ForceOpenFileByPath'](arg1);
}

export function GetDisplayName(arg1) {
  return window['go']['main']['App']['GetDisplayName'](arg1);
}

export function GetPendingFilePath() {
  return window['go']['main']['App']['GetPendingFilePath']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFileByPath(arg1) {
  return window['go']['main']['App']['OpenFileByPath'](arg1);
}

export function OpenNewWindow(arg1) {
  return window['go']['main']['App']['OpenNewWindow'](arg1);
}

export function PrintHTML(arg1) {
  return window['go']['main']['App']['PrintHTML'](arg1);
}

export function PrintText(arg1) {
  return window['go']['main']['App']['PrintText'](arg1);
}

export function QueryAI(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryAI'](arg1, arg2, arg3);
}

export function ReopenWithEncoding(arg1, arg2) {
  return window['go']['main']['App']['ReopenWithEncoding'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileWithEncoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileWithEncoding'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}
